_src_path: gh:con/orinoco-lite-template
project_name: Orinoco Lite Site
project_slug: orinoco-site
site_description: A site built with Orinoco Lite.
repository_slug: example/orinoco-site
site_base_url: https://example.invalid/orinoco-site/
engine_version: 0.2.0rc5
engine_url: https://github.com/con/orinoco-lite-dev/releases/download/v0.2.0rc5/orinoco_lite-0.2.0rc5-py3-none-any.whl
engine_sha256: 61bd84702361179ecf63701d8ce0cd3cd97f382350274d4023a1737a552d032c
runtime_version: 0.2.0rc5
runtime_url: https://github.com/con/orinoco-lite-dev/releases/download/v0.2.0rc5/orinoco-runtime-0.2.0rc5.tar.gz
runtime_sha256: f3a019c326fa2a46549682da4303ba63b645674f64c601b74014af356683c6dd
runtime_manifest_sha256: 7897fcf3e5faebf5d7b6717d37013a6464c90d5eaea4c8bac0781cca1a095d2d
template_source: gh:con/orinoco-lite-template
template_version: v0.2.0rc8
workflow_repository: con/orinoco-lite-dev
workflow_sha: 6bd31daa17293fe7d52966bc1599f66b2ea3420b
workflow_ref: con/orinoco-lite-dev/.github/workflows/orinoco-consumer-ci.yml@6bd31daa17293fe7d52966bc1599f66b2ea3420b
_commit: v0.2.0rc8
