project_name: Orinoco Lite Site
project_slug: orinoco-site
site_description: A site built with Orinoco Lite.
repository_slug: example/orinoco-site
site_base_url: https://example.invalid/orinoco-site/
engine_version: 0.2.0rc6
engine_url: https://github.com/ORINOCO-Lite/orinoco-lite-dev/releases/download/v0.2.0rc6/orinoco_lite-0.2.0rc6-py3-none-any.whl
engine_sha256: "a0e483fffb1793b7870d5ef3af7bd31f0e3cfead09dbdaf0f55623182fd73404"
runtime_version: 0.2.0rc6
runtime_url: https://github.com/ORINOCO-Lite/orinoco-lite-dev/releases/download/v0.2.0rc6/orinoco-runtime-0.2.0rc6.tar.gz
runtime_sha256: "e343d15399f800a721ebf05921625aac2cc78ce2cdcebc45415c3a8e8845c2cd"
runtime_manifest_sha256: "96bec50b154654f2e4288312130a7cabceb68b5d3dcc8fa67e34d216e20d7719"
template_source: gh:ORINOCO-Lite/orinoco-lite-template
template_version: v0.2.0rc10
workflow_repository: ORINOCO-Lite/orinoco-lite-dev
workflow_sha: "6bd31daa17293fe7d52966bc1599f66b2ea3420b"
workflow_ref: ORINOCO-Lite/orinoco-lite-dev/.github/workflows/orinoco-consumer-ci.yml@6bd31daa17293fe7d52966bc1599f66b2ea3420b
